# Generated by Django 2.0.5 on 2018-05-21 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-entryDate']},
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthDay',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cityBirth',
            field=models.CharField(default='南京市', max_length=20, null=True, verbose_name='籍贯市'),
        ),
        migrations.AlterField(
            model_name='person',
            name='depart',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(choices=[('0', '小学'), ('1', '初中'), ('2', '高中'), ('3', '大专'), ('4', '本科'), ('5', '研究生')], default='4', max_length=1, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='person',
            name='graduatedDay',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='毕业日期'),
        ),
        migrations.AlterField(
            model_name='person',
            name='graduatedSchool',
            field=models.CharField(default='大学', max_length=20, null=True, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(choices=[('00', '00'), ('1B', '1B'), ('1A', '1A'), ('2B', '2B'), ('2A', '2A'), ('3B', '3B'), ('3A', '3A'), ('4B', '4B'), ('4A', '4A'), ('5B', '5B'), ('5A', '5A'), ('6B', '6B'), ('6A', '6A'), ('7B', '7B'), ('7A', '7A'), ('8B', '8B'), ('8A', '8A'), ('9B', '9B'), ('9A', '9A'), ('10B', '10B'), ('10A', '10A'), ('11B', '11B'), ('11A', '11A'), ('12B', '12B'), ('12A', '12A')], default='00', max_length=4, verbose_name='岗位级别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='productUnit',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='person',
            name='projectName',
            field=models.CharField(default='0', max_length=20, null=True, verbose_name='项目组名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='provinceBirth',
            field=models.CharField(default='江苏省', max_length=20, null=True, verbose_name='籍贯省份'),
        ),
    ]
