# Generated by Django 2.0.5 on 2018-06-06 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20180521_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRange', models.CharField(blank=True, default='2018Q1', max_length=10, null=True, verbose_name='考核周期')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='绩效得分')),
                ('result', models.CharField(blank=True, max_length=10, null=True, verbose_name='绩效结果')),
                ('appraisers', models.CharField(blank=True, max_length=10, null=True, verbose_name='考评人')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRange', models.CharField(blank=True, default='2018Q1', max_length=10, null=True, verbose_name='考核周期')),
                ('kpi', models.CharField(default='考核指标项内容', max_length=50, verbose_name='考核项')),
                ('kpiValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='考核项得分')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='workStatus',
            field=models.CharField(choices=[('00', '在职'), ('11', '请假'), ('99', '离职')], default='00', max_length=5, verbose_name='工作状态'),
        ),
        migrations.AddField(
            model_name='salary',
            name='applyDate',
            field=models.DateField(default=datetime.date.today, verbose_name='生效月份'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobilePhone',
            field=models.CharField(default='18600000000', max_length=15, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='person',
            name='userName',
            field=models.CharField(default='张三无名氏', max_length=15, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='workNo',
            field=models.CharField(default='B-12345', max_length=15, verbose_name='公司工号'),
        ),
        migrations.AddField(
            model_name='performacedetail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Person', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='performace',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Person', verbose_name='员工'),
        ),
    ]
